FROM ppc64le/ubuntu:xenial
MAINTAINER pradipta.banerjee@gmail.com

RUN apt-get update -y && \
    apt-get install -y ca-certificates &&\
    apt-get clean -y

# cAdvisor discovery via external files.
VOLUME /var/run/heapster/hosts
ADD heapster /heapster
ADD eventer /eventer

ENTRYPOINT ["/heapster"]
